name: Lint and Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
jobs:
  lint:
    name: lint
    strategy:
      matrix:
        toolchain: [stable]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache toolchain
        uses: Swatinem/rust-cache@v1
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
            override: true
            components: rustfmt, clippy
      - name: Check build
        run: |
          make check
      - name: Lint
        run: |
          make lint
  test:
    name: test
    strategy:
      fail-fast: false
      matrix:
        os: 
          # wait fix https://github.com/denoland/deno_bindgen/issues/91
          # - windows-latest
          - macos-latest
          - ubuntu-latest
        toolchain: [stable]
        deno_version: [v1.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install expat
          sudo apt install libxml2-dev
          sudo apt install pkg-config libasound2-dev libssl-dev cmake libfreetype6-dev libexpat1-dev libxcb-composite0-dev
      - uses: actions/checkout@v2
      - name: Cache toolchain
        uses: Swatinem/rust-cache@v1
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
            override: true
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno_version }}
      - name: Install deno_bindgen
        run: |
          # FIXME: Install from GitHub as the latest commit supports FFI destructive changes but has not been released. 
          # deno install -Afq -n deno_bindgen https://deno.land/x/deno_bindgen/cli.ts
          deno install -Afq -n deno_bindgen https://raw.githubusercontent.com/denoland/deno_bindgen/main/cli.ts
      - name: Test
        run: |
          make test
